// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtYDb8j0Mmir7XSSI37AqnKjR595Adexc',
    appId: '1:390988238481:web:359d29c845079ac60e7930',
    messagingSenderId: '390988238481',
    projectId: 'servicesapp-db857',
    authDomain: 'servicesapp-db857.firebaseapp.com',
    storageBucket: 'servicesapp-db857.appspot.com',
    measurementId: 'G-SR1VPQE4DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXT3W_ezgPuEE7S0E2dPtOAGiOSxRLVtQ',
    appId: '1:390988238481:android:5b525e7f90886ace0e7930',
    messagingSenderId: '390988238481',
    projectId: 'servicesapp-db857',
    storageBucket: 'servicesapp-db857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlKi0B12XTO2x95OV1G6DsLBuC98ARSXw',
    appId: '1:390988238481:ios:11aa31e3de5732cb0e7930',
    messagingSenderId: '390988238481',
    projectId: 'servicesapp-db857',
    storageBucket: 'servicesapp-db857.appspot.com',
    iosBundleId: 'com.example.servicesAndroidApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlKi0B12XTO2x95OV1G6DsLBuC98ARSXw',
    appId: '1:390988238481:ios:11aa31e3de5732cb0e7930',
    messagingSenderId: '390988238481',
    projectId: 'servicesapp-db857',
    storageBucket: 'servicesapp-db857.appspot.com',
    iosBundleId: 'com.example.servicesAndroidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtYDb8j0Mmir7XSSI37AqnKjR595Adexc',
    appId: '1:390988238481:web:6e2b32fbf153910d0e7930',
    messagingSenderId: '390988238481',
    projectId: 'servicesapp-db857',
    authDomain: 'servicesapp-db857.firebaseapp.com',
    storageBucket: 'servicesapp-db857.appspot.com',
    measurementId: 'G-LPNHELY4HE',
  );

}